# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('int', '0002_auto_20161111_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country_code',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_post',
            field=models.NullBooleanField(db_index=True),
        ),
    ]
